/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class ADSR {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ADSR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ADSR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_ADSR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ADSR() {
    this(MWEngineCoreJNI.new_ADSR__SWIG_0(), true);
  }

  public ADSR(float attackTime, float decayTime, float sustainLevel, float releaseTime) {
    this(MWEngineCoreJNI.new_ADSR__SWIG_1(attackTime, decayTime, sustainLevel, releaseTime), true);
  }

  public ADSR clone() {
    long cPtr = MWEngineCoreJNI.ADSR_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ADSR(cPtr, false);
  }

  public void cloneEnvelopes(ADSR source) {
    MWEngineCoreJNI.ADSR_cloneEnvelopes(swigCPtr, this, ADSR.getCPtr(source), source);
  }

  public float getAttackTime() {
    return MWEngineCoreJNI.ADSR_getAttackTime(swigCPtr, this);
  }

  public float getDecayTime() {
    return MWEngineCoreJNI.ADSR_getDecayTime(swigCPtr, this);
  }

  public float getSustainLevel() {
    return MWEngineCoreJNI.ADSR_getSustainLevel(swigCPtr, this);
  }

  public float getReleaseTime() {
    return MWEngineCoreJNI.ADSR_getReleaseTime(swigCPtr, this);
  }

  public void setAttackTime(float aValue) {
    MWEngineCoreJNI.ADSR_setAttackTime(swigCPtr, this, aValue);
  }

  public void setDecayTime(float aValue) {
    MWEngineCoreJNI.ADSR_setDecayTime(swigCPtr, this, aValue);
  }

  public void setSustainLevel(float aValue) {
    MWEngineCoreJNI.ADSR_setSustainLevel(swigCPtr, this, aValue);
  }

  public void setReleaseTime(float aValue) {
    MWEngineCoreJNI.ADSR_setReleaseTime(swigCPtr, this, aValue);
  }

  public int getReleaseStartOffset() {
    return MWEngineCoreJNI.ADSR_getReleaseStartOffset(swigCPtr, this);
  }

  public int getReleaseDuration() {
    return MWEngineCoreJNI.ADSR_getReleaseDuration(swigCPtr, this);
  }

  public void apply(SWIGTYPE_p_AudioBuffer inputBuffer, BaseSynthEvent synthEvent, int writeOffset) {
    MWEngineCoreJNI.ADSR_apply(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(inputBuffer), BaseSynthEvent.getCPtr(synthEvent), synthEvent, writeOffset);
  }

  public void setDurations(int attackDuration, int decayDuration, int releaseDuration, int bufferLength) {
    MWEngineCoreJNI.ADSR_setDurations(swigCPtr, this, attackDuration, decayDuration, releaseDuration, bufferLength);
  }

}
