/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class ChannelGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChannelGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_ChannelGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChannelGroup() {
    this(MWEngineCoreJNI.new_ChannelGroup__SWIG_0(), true);
  }

  public ChannelGroup(float volume) {
    this(MWEngineCoreJNI.new_ChannelGroup__SWIG_1(volume), true);
  }

  public float getVolume() {
    return MWEngineCoreJNI.ChannelGroup_getVolume(swigCPtr, this);
  }

  public float getVolumeLogarithmic() {
    return MWEngineCoreJNI.ChannelGroup_getVolumeLogarithmic(swigCPtr, this);
  }

  public void setVolume(float value) {
    MWEngineCoreJNI.ChannelGroup_setVolume(swigCPtr, this, value);
  }

  public ProcessingChain getProcessingChain() {
    long cPtr = MWEngineCoreJNI.ChannelGroup_getProcessingChain(swigCPtr, this);
    return (cPtr == 0) ? null : new ProcessingChain(cPtr, false);
  }

  public boolean addAudioChannel(AudioChannel audioChannel) {
    return MWEngineCoreJNI.ChannelGroup_addAudioChannel(swigCPtr, this, AudioChannel.getCPtr(audioChannel), audioChannel);
  }

  public boolean removeAudioChannel(AudioChannel audioChannel) {
    return MWEngineCoreJNI.ChannelGroup_removeAudioChannel(swigCPtr, this, AudioChannel.getCPtr(audioChannel), audioChannel);
  }

  public boolean containsAudioChannel(AudioChannel audioChannel) {
    return MWEngineCoreJNI.ChannelGroup_containsAudioChannel(swigCPtr, this, AudioChannel.getCPtr(audioChannel), audioChannel);
  }

  public boolean applyEffectsToChannels(SWIGTYPE_p_AudioBuffer bufferToMixInto) {
    return MWEngineCoreJNI.ChannelGroup_applyEffectsToChannels(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(bufferToMixInto));
  }

}
