/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class Decimator extends BaseProcessor {
  private transient long swigCPtr;

  protected Decimator(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.Decimator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Decimator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_Decimator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Decimator(int bits, float rate) {
    this(MWEngineCoreJNI.new_Decimator(bits, rate), true);
  }

  public String getType() {
    return MWEngineCoreJNI.Decimator_getType(swigCPtr, this);
  }

  public int getBits() {
    return MWEngineCoreJNI.Decimator_getBits(swigCPtr, this);
  }

  public void setBits(int value) {
    MWEngineCoreJNI.Decimator_setBits(swigCPtr, this, value);
  }

  public float getRate() {
    return MWEngineCoreJNI.Decimator_getRate(swigCPtr, this);
  }

  public void setRate(float value) {
    MWEngineCoreJNI.Decimator_setRate(swigCPtr, this, value);
  }

}
