/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class DrumInstrument extends BaseInstrument {
  private transient long swigCPtr;

  protected DrumInstrument(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.DrumInstrument_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DrumInstrument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_DrumInstrument(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DrumInstrument() {
    this(MWEngineCoreJNI.new_DrumInstrument(), true);
  }

  public SWIGTYPE_p_std__vectorT_MWEngine__BaseAudioEvent_p_t getEvents() {
    long cPtr = MWEngineCoreJNI.DrumInstrument_getEvents(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_MWEngine__BaseAudioEvent_p_t(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_MWEngine__BaseAudioEvent_p_t getEventsForPattern(int patternNum) {
    long cPtr = MWEngineCoreJNI.DrumInstrument_getEventsForPattern(swigCPtr, this, patternNum);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_MWEngine__BaseAudioEvent_p_t(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_MWEngine__BaseAudioEvent_p_t getEventsForActivePattern() {
    long cPtr = MWEngineCoreJNI.DrumInstrument_getEventsForActivePattern(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_MWEngine__BaseAudioEvent_p_t(cPtr, false);
  }

  public void setDrumTimbre(int value) {
    MWEngineCoreJNI.DrumInstrument_drumTimbre_set(swigCPtr, this, value);
  }

  public int getDrumTimbre() {
    return MWEngineCoreJNI.DrumInstrument_drumTimbre_get(swigCPtr, this);
  }

  public void setDrumPatterns(SWIGTYPE_p_std__vectorT_MWEngine__DrumPattern_p_t value) {
    MWEngineCoreJNI.DrumInstrument_drumPatterns_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_MWEngine__DrumPattern_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_MWEngine__DrumPattern_p_t getDrumPatterns() {
    long cPtr = MWEngineCoreJNI.DrumInstrument_drumPatterns_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_MWEngine__DrumPattern_p_t(cPtr, false);
  }

  public void setActiveDrumPattern(int value) {
    MWEngineCoreJNI.DrumInstrument_activeDrumPattern_set(swigCPtr, this, value);
  }

  public int getActiveDrumPattern() {
    return MWEngineCoreJNI.DrumInstrument_activeDrumPattern_get(swigCPtr, this);
  }

  public void setROsc(RouteableOscillator value) {
    MWEngineCoreJNI.DrumInstrument_rOsc_set(swigCPtr, this, RouteableOscillator.getCPtr(value), value);
  }

  public RouteableOscillator getROsc() {
    long cPtr = MWEngineCoreJNI.DrumInstrument_rOsc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RouteableOscillator(cPtr, false);
  }

  public boolean hasEvents() {
    return MWEngineCoreJNI.DrumInstrument_hasEvents(swigCPtr, this);
  }

  public void updateEvents() {
    MWEngineCoreJNI.DrumInstrument_updateEvents(swigCPtr, this);
  }

  public void clearEvents() {
    MWEngineCoreJNI.DrumInstrument_clearEvents(swigCPtr, this);
  }

  public boolean removeEvent(BaseAudioEvent audioEvent, boolean isLiveEvent) {
    return MWEngineCoreJNI.DrumInstrument_removeEvent(swigCPtr, this, BaseAudioEvent.getCPtr(audioEvent), audioEvent, isLiveEvent);
  }

  public DrumPattern getDrumPattern(int patternNum) {
    long cPtr = MWEngineCoreJNI.DrumInstrument_getDrumPattern(swigCPtr, this, patternNum);
    return (cPtr == 0) ? null : new DrumPattern(cPtr, false);
  }

  public int setDrumPattern(DrumPattern pattern) {
    return MWEngineCoreJNI.DrumInstrument_setDrumPattern(swigCPtr, this, DrumPattern.getCPtr(pattern), pattern);
  }

}
