/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class Glitcher extends BaseProcessor {
  private transient long swigCPtr;

  protected Glitcher(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.Glitcher_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Glitcher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_Glitcher(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Glitcher(int amountOfChannels, int fragmentLengthInMilliseconds) {
    this(MWEngineCoreJNI.new_Glitcher(amountOfChannels, fragmentLengthInMilliseconds), true);
  }

  public String getType() {
    return MWEngineCoreJNI.Glitcher_getType(swigCPtr, this);
  }

  public void setRecording(boolean value) {
    MWEngineCoreJNI.Glitcher_setRecording(swigCPtr, this, value);
  }

  public void setPlayback(boolean value) {
    MWEngineCoreJNI.Glitcher_setPlayback(swigCPtr, this, value);
  }

  public void setPlaybackRange(int bufferStartPos, int bufferEndPos) {
    MWEngineCoreJNI.Glitcher_setPlaybackRange(swigCPtr, this, bufferStartPos, bufferEndPos);
  }

  public int getSampleLength() {
    return MWEngineCoreJNI.Glitcher_getSampleLength(swigCPtr, this);
  }

}
