/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class Limiter extends BaseProcessor {
  private transient long swigCPtr;

  protected Limiter(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.Limiter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Limiter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_Limiter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Limiter() {
    this(MWEngineCoreJNI.new_Limiter__SWIG_0(), true);
  }

  public Limiter(float attackMs, float releaseMs, float thresholdDb) {
    this(MWEngineCoreJNI.new_Limiter__SWIG_1(attackMs, releaseMs, thresholdDb), true);
  }

  public String getType() {
    return MWEngineCoreJNI.Limiter_getType(swigCPtr, this);
  }

  public float getAttack() {
    return MWEngineCoreJNI.Limiter_getAttack(swigCPtr, this);
  }

  public void setAttack(float attackMs) {
    MWEngineCoreJNI.Limiter_setAttack(swigCPtr, this, attackMs);
  }

  public float getRelease() {
    return MWEngineCoreJNI.Limiter_getRelease(swigCPtr, this);
  }

  public void setRelease(float releaseMs) {
    MWEngineCoreJNI.Limiter_setRelease(swigCPtr, this, releaseMs);
  }

  public float getThreshold() {
    return MWEngineCoreJNI.Limiter_getThreshold(swigCPtr, this);
  }

  public void setThreshold(float thresholdDb) {
    MWEngineCoreJNI.Limiter_setThreshold(swigCPtr, this, thresholdDb);
  }

  public float getLinearGR() {
    return MWEngineCoreJNI.Limiter_getLinearGR(swigCPtr, this);
  }

}
