/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class LowPassFilter extends BaseProcessor {
  private transient long swigCPtr;

  protected LowPassFilter(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.LowPassFilter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LowPassFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_LowPassFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LowPassFilter(float cutoff) {
    this(MWEngineCoreJNI.new_LowPassFilter(cutoff), true);
  }

  public String getType() {
    return MWEngineCoreJNI.LowPassFilter_getType(swigCPtr, this);
  }

  public float getCutoff() {
    return MWEngineCoreJNI.LowPassFilter_getCutoff(swigCPtr, this);
  }

  public void setCutoff(float value) {
    MWEngineCoreJNI.LowPassFilter_setCutoff(swigCPtr, this, value);
  }

}
