/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class OscillatorProperties {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OscillatorProperties(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OscillatorProperties obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_OscillatorProperties(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OscillatorProperties(int aWaveform, float aDetune, int aOctaveShift, int aFineShift) {
    this(MWEngineCoreJNI.new_OscillatorProperties(aWaveform, aDetune, aOctaveShift, aFineShift), true);
  }

  public int getWaveform() {
    return MWEngineCoreJNI.OscillatorProperties_getWaveform(swigCPtr, this);
  }

  public void setWaveform(int aWaveform) {
    MWEngineCoreJNI.OscillatorProperties_setWaveform(swigCPtr, this, aWaveform);
  }

  public void setCustomWaveform(String waveformId) {
    MWEngineCoreJNI.OscillatorProperties_setCustomWaveform(swigCPtr, this, waveformId);
  }

  public void setDetune(float value) {
    MWEngineCoreJNI.OscillatorProperties_detune_set(swigCPtr, this, value);
  }

  public float getDetune() {
    return MWEngineCoreJNI.OscillatorProperties_detune_get(swigCPtr, this);
  }

  public void setOctaveShift(int value) {
    MWEngineCoreJNI.OscillatorProperties_octaveShift_set(swigCPtr, this, value);
  }

  public int getOctaveShift() {
    return MWEngineCoreJNI.OscillatorProperties_octaveShift_get(swigCPtr, this);
  }

  public void setFineShift(int value) {
    MWEngineCoreJNI.OscillatorProperties_fineShift_set(swigCPtr, this, value);
  }

  public int getFineShift() {
    return MWEngineCoreJNI.OscillatorProperties_fineShift_get(swigCPtr, this);
  }

  public void setWaveTable(SWIGTYPE_p_WaveTable value) {
    MWEngineCoreJNI.OscillatorProperties_waveTable_set(swigCPtr, this, SWIGTYPE_p_WaveTable.getCPtr(value));
  }

  public SWIGTYPE_p_WaveTable getWaveTable() {
    long cPtr = MWEngineCoreJNI.OscillatorProperties_waveTable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_WaveTable(cPtr, false);
  }

}
