/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class Phaser extends BaseProcessor {
  private transient long swigCPtr;

  protected Phaser(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.Phaser_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Phaser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_Phaser(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Phaser(float aRate, float aFeedback, float aDepth, float aMinFreq, float aMaxFreq) {
    this(MWEngineCoreJNI.new_Phaser__SWIG_0(aRate, aFeedback, aDepth, aMinFreq, aMaxFreq), true);
  }

  public Phaser(float aRate, float aFeedback, float aDepth, float aMinFreq, float aMaxFreq, int amountOfChannels) {
    this(MWEngineCoreJNI.new_Phaser__SWIG_1(aRate, aFeedback, aDepth, aMinFreq, aMaxFreq, amountOfChannels), true);
  }

  public String getType() {
    return MWEngineCoreJNI.Phaser_getType(swigCPtr, this);
  }

  public void setDepth(float depth) {
    MWEngineCoreJNI.Phaser_setDepth(swigCPtr, this, depth);
  }

  public float getDepth() {
    return MWEngineCoreJNI.Phaser_getDepth(swigCPtr, this);
  }

  public void setFeedback(float fb) {
    MWEngineCoreJNI.Phaser_setFeedback(swigCPtr, this, fb);
  }

  public float getFeedback() {
    return MWEngineCoreJNI.Phaser_getFeedback(swigCPtr, this);
  }

  public void setRate(float aRate) {
    MWEngineCoreJNI.Phaser_setRate(swigCPtr, this, aRate);
  }

  public float getRate() {
    return MWEngineCoreJNI.Phaser_getRate(swigCPtr, this);
  }

  public void setRange(float aMin, float aMax) {
    MWEngineCoreJNI.Phaser_setRange(swigCPtr, this, aMin, aMax);
  }

}
