/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class Pitch {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Pitch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pitch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_Pitch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double note(String aNote, int aOctave) {
    return MWEngineCoreJNI.Pitch_note(aNote, aOctave);
  }

  public Pitch() {
    this(MWEngineCoreJNI.new_Pitch(), true);
  }

  public final static double C = MWEngineCoreJNI.Pitch_C_get();
  public final static double C_SHARP = MWEngineCoreJNI.Pitch_C_SHARP_get();
  public final static double D = MWEngineCoreJNI.Pitch_D_get();
  public final static double D_SHARP = MWEngineCoreJNI.Pitch_D_SHARP_get();
  public final static double E = MWEngineCoreJNI.Pitch_E_get();
  public final static double F = MWEngineCoreJNI.Pitch_F_get();
  public final static double F_SHARP = MWEngineCoreJNI.Pitch_F_SHARP_get();
  public final static double G = MWEngineCoreJNI.Pitch_G_get();
  public final static double G_SHARP = MWEngineCoreJNI.Pitch_G_SHARP_get();
  public final static double A = MWEngineCoreJNI.Pitch_A_get();
  public final static double A_SHARP = MWEngineCoreJNI.Pitch_A_SHARP_get();
  public final static double B = MWEngineCoreJNI.Pitch_B_get();
}
