/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class Reverb extends BaseProcessor {
  private transient long swigCPtr;

  protected Reverb(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.Reverb_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Reverb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_Reverb(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Reverb(float size, float hfDamp, float mix, float output) {
    this(MWEngineCoreJNI.new_Reverb(size, hfDamp, mix, output), true);
  }

  public String getType() {
    return MWEngineCoreJNI.Reverb_getType(swigCPtr, this);
  }

  public float getSize() {
    return MWEngineCoreJNI.Reverb_getSize(swigCPtr, this);
  }

  public void setSize(float value) {
    MWEngineCoreJNI.Reverb_setSize(swigCPtr, this, value);
  }

  public float getHFDamp() {
    return MWEngineCoreJNI.Reverb_getHFDamp(swigCPtr, this);
  }

  public void setHFDamp(float value) {
    MWEngineCoreJNI.Reverb_setHFDamp(swigCPtr, this, value);
  }

  public float getMix() {
    return MWEngineCoreJNI.Reverb_getMix(swigCPtr, this);
  }

  public void setMix(float value) {
    MWEngineCoreJNI.Reverb_setMix(swigCPtr, this, value);
  }

  public float getOutput() {
    return MWEngineCoreJNI.Reverb_getOutput(swigCPtr, this);
  }

  public void setOutput(float value) {
    MWEngineCoreJNI.Reverb_setOutput(swigCPtr, this, value);
  }

}
