/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class SampleUtility {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SampleUtility(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleUtility obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_SampleUtility(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void pitchShift(SampleEvent sampleEvent, float semitones) {
    MWEngineCoreJNI.SampleUtility_pitchShift(SampleEvent.getCPtr(sampleEvent), sampleEvent, semitones);
  }

  public SampleUtility() {
    this(MWEngineCoreJNI.new_SampleUtility(), true);
  }

}
