/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class AllPassDelay {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AllPassDelay(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AllPassDelay obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_AllPassDelay(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AllPassDelay() {
    this(MWEngineCoreJNI.new_AllPassDelay(), true);
  }

  public void delay(SWIGTYPE_p_SAMPLE_TYPE aDelay) {
    MWEngineCoreJNI.AllPassDelay_delay(swigCPtr, this, SWIGTYPE_p_SAMPLE_TYPE.getCPtr(aDelay));
  }

  public SWIGTYPE_p_SAMPLE_TYPE update(SWIGTYPE_p_SAMPLE_TYPE aSample) {
    return new SWIGTYPE_p_SAMPLE_TYPE(MWEngineCoreJNI.AllPassDelay_update(swigCPtr, this, SWIGTYPE_p_SAMPLE_TYPE.getCPtr(aSample)), true);
  }

}
