/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class BaseProcessor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BaseProcessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_BaseProcessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BaseProcessor() {
    this(MWEngineCoreJNI.new_BaseProcessor(), true);
  }

  public String getType() {
    return MWEngineCoreJNI.BaseProcessor_getType(swigCPtr, this);
  }

}
