/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class Filter extends BaseProcessor {
  private transient long swigCPtr;

  protected Filter(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.Filter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Filter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_Filter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Filter(float aCutoffFrequency, float aResonance, float aMinFreq, float aMaxFreq, int numChannels) {
    this(MWEngineCoreJNI.new_Filter__SWIG_0(aCutoffFrequency, aResonance, aMinFreq, aMaxFreq, numChannels), true);
  }

  public Filter() {
    this(MWEngineCoreJNI.new_Filter__SWIG_1(), true);
  }

  public String getType() {
    return MWEngineCoreJNI.Filter_getType(swigCPtr, this);
  }

  public void setCutoff(float frequency) {
    MWEngineCoreJNI.Filter_setCutoff(swigCPtr, this, frequency);
  }

  public float getCutoff() {
    return MWEngineCoreJNI.Filter_getCutoff(swigCPtr, this);
  }

  public void setResonance(float resonance) {
    MWEngineCoreJNI.Filter_setResonance(swigCPtr, this, resonance);
  }

  public float getResonance() {
    return MWEngineCoreJNI.Filter_getResonance(swigCPtr, this);
  }

  public boolean hasLFO() {
    return MWEngineCoreJNI.Filter_hasLFO(swigCPtr, this);
  }

  public LFO getLFO() {
    long cPtr = MWEngineCoreJNI.Filter_getLFO(swigCPtr, this);
    return (cPtr == 0) ? null : new LFO(cPtr, false);
  }

  public void setLFO(LFO lfo) {
    MWEngineCoreJNI.Filter_setLFO(swigCPtr, this, LFO.getCPtr(lfo), lfo);
  }

}
