/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class JavaUtilities {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JavaUtilities(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JavaUtilities obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_JavaUtilities(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static boolean createSampleFromFile(String aKey, String aWAVFilePath) {
    return MWEngineCoreJNI.JavaUtilities_createSampleFromFile(aKey, aWAVFilePath);
  }

  public static boolean createSampleFromAsset(String aKey, java.lang.Object assetManager, String cacheDir, String assetName) {
    return MWEngineCoreJNI.JavaUtilities_createSampleFromAsset(aKey, assetManager, cacheDir, assetName);
  }

  public static void createSampleFromBuffer(String aKey, int aBufferLength, int aChannelAmount, double[] aBuffer, double[] aOptRightBuffer) {
    MWEngineCoreJNI.JavaUtilities_createSampleFromBuffer(aKey, aBufferLength, aChannelAmount, aBuffer, aOptRightBuffer);
  }

  public static void cacheTable(int tableLength, int waveformType, String tableId) {
    MWEngineCoreJNI.JavaUtilities_cacheTable__SWIG_0(tableLength, waveformType, tableId);
  }

  public static void cacheTable(int tableLength, int waveformType, String tableId, double[] aBuffer) {
    MWEngineCoreJNI.JavaUtilities_cacheTable__SWIG_1(tableLength, waveformType, tableId, aBuffer);
  }

  public static boolean createTableFromFile(String tableId, String aWAVFilePath) {
    return MWEngineCoreJNI.JavaUtilities_createTableFromFile(tableId, aWAVFilePath);
  }

  public static void setCpuCores(int[] cpuCores, int amountOfCores) {
    MWEngineCoreJNI.JavaUtilities_setCpuCores(cpuCores, amountOfCores);
  }

  public JavaUtilities() {
    this(MWEngineCoreJNI.new_JavaUtilities(), true);
  }

}
