/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public interface MWEngineCoreConstants {
  public final static double M_PI = MWEngineCoreJNI.M_PI_get();
  public final static int MAX_FRAME_LENGTH = MWEngineCoreJNI.MAX_FRAME_LENGTH_get();
}
