/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class PercussionTypes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PercussionTypes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PercussionTypes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_PercussionTypes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PercussionTypes() {
    this(MWEngineCoreJNI.new_PercussionTypes(), true);
  }

  public enum Types {
    KICK_808,
    STICK,
    SNARE,
    HI_HAT;

    public final int swigValue() {
      return swigValue;
    }

    public static Types swigToEnum(int swigValue) {
      Types[] swigValues = Types.class.getEnumConstants();
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (Types swigEnum : swigValues)
        if (swigEnum.swigValue == swigValue)
          return swigEnum;
      throw new IllegalArgumentException("No enum " + Types.class + " with value " + swigValue);
    }

    @SuppressWarnings("unused")
    private Types() {
      this.swigValue = SwigNext.next++;
    }

    @SuppressWarnings("unused")
    private Types(int swigValue) {
      this.swigValue = swigValue;
      SwigNext.next = swigValue+1;
    }

    @SuppressWarnings("unused")
    private Types(Types swigEnum) {
      this.swigValue = swigEnum.swigValue;
      SwigNext.next = this.swigValue+1;
    }

    private final int swigValue;

    private static class SwigNext {
      private static int next = 0;
    }
  }

}
