/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class ReverbSM extends BaseProcessor {
  private transient long swigCPtr;

  protected ReverbSM(long cPtr, boolean cMemoryOwn) {
    super(MWEngineCoreJNI.ReverbSM_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReverbSM obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_ReverbSM(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ReverbSM() {
    this(MWEngineCoreJNI.new_ReverbSM(), true);
  }

  public String getType() {
    return MWEngineCoreJNI.ReverbSM_getType(swigCPtr, this);
  }

  public void mute() {
    MWEngineCoreJNI.ReverbSM_mute(swigCPtr, this);
  }

  public void setRoomSize(float value) {
    MWEngineCoreJNI.ReverbSM_setRoomSize(swigCPtr, this, value);
  }

  public float getRoomSize() {
    return MWEngineCoreJNI.ReverbSM_getRoomSize(swigCPtr, this);
  }

  public void setDamp(float value) {
    MWEngineCoreJNI.ReverbSM_setDamp(swigCPtr, this, value);
  }

  public float getDamp() {
    return MWEngineCoreJNI.ReverbSM_getDamp(swigCPtr, this);
  }

  public void setWet(float value) {
    MWEngineCoreJNI.ReverbSM_setWet(swigCPtr, this, value);
  }

  public float getWet() {
    return MWEngineCoreJNI.ReverbSM_getWet(swigCPtr, this);
  }

  public void setDry(float value) {
    MWEngineCoreJNI.ReverbSM_setDry(swigCPtr, this, value);
  }

  public float getDry() {
    return MWEngineCoreJNI.ReverbSM_getDry(swigCPtr, this);
  }

  public void setWidth(float value) {
    MWEngineCoreJNI.ReverbSM_setWidth(swigCPtr, this, value);
  }

  public float getWidth() {
    return MWEngineCoreJNI.ReverbSM_getWidth(swigCPtr, this);
  }

  public void setMode(float value) {
    MWEngineCoreJNI.ReverbSM_setMode(swigCPtr, this, value);
  }

  public float getMode() {
    return MWEngineCoreJNI.ReverbSM_getMode(swigCPtr, this);
  }

}
