/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class RouteableOscillator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RouteableOscillator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RouteableOscillator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MWEngineCoreJNI.delete_RouteableOscillator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RouteableOscillator() {
    this(MWEngineCoreJNI.new_RouteableOscillator(), true);
  }

  public void setDestination(int value) {
    MWEngineCoreJNI.RouteableOscillator_destination_set(swigCPtr, this, value);
  }

  public int getDestination() {
    return MWEngineCoreJNI.RouteableOscillator_destination_get(swigCPtr, this);
  }

  public void setSpeed(float value) {
    MWEngineCoreJNI.RouteableOscillator_speed_set(swigCPtr, this, value);
  }

  public float getSpeed() {
    return MWEngineCoreJNI.RouteableOscillator_speed_get(swigCPtr, this);
  }

  public void setWave(int value) {
    MWEngineCoreJNI.RouteableOscillator_wave_set(swigCPtr, this, value);
  }

  public int getWave() {
    return MWEngineCoreJNI.RouteableOscillator_wave_get(swigCPtr, this);
  }

  public void linkOscillator() {
    MWEngineCoreJNI.RouteableOscillator_linkOscillator(swigCPtr, this);
  }

  public void unlinkOscillator() {
    MWEngineCoreJNI.RouteableOscillator_unlinkOscillator(swigCPtr, this);
  }

  public boolean isLinked() {
    return MWEngineCoreJNI.RouteableOscillator_isLinked(swigCPtr, this);
  }

  public LFO getLinkedOscillator() {
    long cPtr = MWEngineCoreJNI.RouteableOscillator_getLinkedOscillator(swigCPtr, this);
    return (cPtr == 0) ? null : new LFO(cPtr, false);
  }

}
